# Generated by Django 4.2.7 on 2026-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_rename_expression_calculation_parsed_math_expression_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['user', '-created_at'], name='solver_calc_user_id_feb26d_idx'),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['operation_type'], name='solver_calc_operati_d43767_idx'),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['-created_at'], name='solver_calc_created_ce72d7_idx'),
        ),
        migrations.AddIndex(
            model_name='calculation',
            index=models.Index(fields=['user', 'operation_type'], name='solver_calc_user_id_763a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='graph',
            index=models.Index(fields=['user', '-created_at'], name='solver_grap_user_id_ab5496_idx'),
        ),
        migrations.AddIndex(
            model_name='graph',
            index=models.Index(fields=['-created_at'], name='solver_grap_created_8d6888_idx'),
        ),
    ]
