# Generated by Django 4.2.7 on 2026-01-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_calculation_solver_calc_user_id_feb26d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='x_range',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='y_range',
        ),
        migrations.AddField(
            model_name='calculation',
            name='latex_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='graph',
            name='x_max',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='graph',
            name='x_min',
            field=models.FloatField(default=-10.0),
        ),
        migrations.AddField(
            model_name='graph',
            name='y_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='y_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='expression',
            field=models.TextField(max_length=1000),
        ),
    ]
